name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: "Name of the repository to be created"
        required: true
        default: ""

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Creating GitHub Organization Repository
        uses: f1lander/create-repository-action@v1.0.2
        id: create-repo
        with:
          name: "${{ github.event.inputs.repo-name }}"
          org: themnd
          private: false
          access-token: "${{ secrets.ORG_ADMIN_TOKEN }}"
      - name: Log URL to the repo
        run: echo "The new repo is ${{ steps.create-repo.outputs.repo-url }}"
