name: GitHub Actions Demo
run-name: ${{ github.actor }} is creating ${{ github.event_name }} 🚀

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: "Name of the repository to be created"
        required: true
        default: ""

jobs:
  create-repo:
    runs-on: ubuntu-latest
    env:
      org-name: themnd
    steps:
      - run: echo "🎉 ${{ github.event_name }} is creating ${{env.repo-url}}."
        env:
          repo-url: https://github.com/${{env.org-name}}/${{github.event.inputs.repo-name}}
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Creating GitHub Organization Repository
        uses: f1lander/create-repository-action@v1.0.2
        id: create-repo
        with:
          name: "${{ github.event.inputs.repo-name }}"
          access-token: "${{ secrets.ORG_ADMIN_TOKEN }}"
      - run: echo "🎉 https://github.com/${{env.org-name}}/${{github.event.inputs.repo-name}} has been created!"
      - run: echo "🎉 ${{env.repo-url}} has been created!"
