name: GitHub Actions Demo
run-name: ${{ github.actor }} is creating a new repository 🚀

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: "Name of the repository to be created"
        required: true
        default: ""

jobs:
  create-repo:
    runs-on: ubuntu-latest
    env:
      org-name: themnd
      repo-url: https://github.com/themnd/${{github.event.inputs.repo-name}}
    steps:
      - run: echo "We are about to create ${{env.repo-url}}"
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Creating GitHub Organization Repository
        uses: f1lander/create-repository-action@v1.0.2
        id: create-repo
        with:
          name: "${{ github.event.inputs.repo-name }}"
          access-token: "${{ secrets.ORG_ADMIN_TOKEN }}"
      - run: echo "🎉 ${{env.repo-url}} has been created!"
