name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
jobs:
  CreateAdmRepo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
